{{- if .Values.mailings.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mailings-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: mailings-service
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
{{- end }}
