{{- if .Values.promotions.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotions-service
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.promotions.replicaCount }}
  selector:
    matchLabels:
      app: promotions-service
  template:
    metadata:
      annotations:
        {{- if .Values.promotions.vault.enabled }}
        vault.security.banzaicloud.io/vault-addr: "http://vault:8200"
        vault.security.banzaicloud.io/vault-path: "order-system"
        vault.security.banzaicloud.io/vault-role: "order-system"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        {{- end }}
      labels:
        app: promotions-service
    spec:
      containers:
      - name: promotions-service
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.promotions.image.repository }}:{{ .Values.promotions.image.tag }}"
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:19092"
        - name: KAFKA_ORDERS_TOPIC
          value: "orders"
        - name: KAFKA_GROUP_ID
          value: "promotions-service"
        {{- if .Values.promotions.vault.enabled }}
        - name: POSTGRES_CONNECTION_STRING
          value: "vault:order-system/data/promotions#POSTGRES_CONNECTION_STRING"
        {{- end }}
{{- end }}
