{{- if and .Values.promotions.enabled .Values.promotions.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: promotions-service
  namespace: {{ .Values.global.namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.promotions.ingress.className }}
spec:
  rules:
  - host: {{ .Values.promotions.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: promotions-service
            port:
              number: 8080
{{- end }}
