{{- if .Values.promotions.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: promotions-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: promotions-service
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
{{- end }}
