apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: default
spec:
  metrics:
  - name: success-rate
    interval: 30s
    successCondition: result[0] >= 0.95
    failureCondition: result[0] < 0.95
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus-server.prometheus.svc.cluster.local:9090
        query: |
          sum(rate(nginx_ingress_controller_requests{service="processing-orders-api",status!~"5.*"}[5m])) / 
          sum(rate(nginx_ingress_controller_requests{service="processing-orders-api"}[5m]))
