apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: processing-orders-api
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: processing-orders-api
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: "http://vault.vault:8200"
        vault.security.banzaicloud.io/vault-path: "order-system"
        vault.security.banzaicloud.io/vault-role: "default"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
      labels:
        app: processing-orders-api
    spec:
      containers:
      - name: processing-orders-api
        image: processing-orders-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ConnectionStrings__OrdersDb
          value: "vault:order-system/data/processing-orders#ConnectionStrings.OrdersDb"
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 30s}
      - setWeight: 50
      - pause: {duration: 30s}
      canaryService: processing-orders-api-canary
      stableService: processing-orders-api-stable
  revisionHistoryLimit: 5
