apiVersion: v1
kind: Service
metadata:
  name: processing-orders-api
  namespace: default
spec:
  selector:
    app: processing-orders-api
  ports:
  - port: 80
    targetPort: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: processing-orders-api-canary
  namespace: default
spec:
  selector:
    app: processing-orders-api
  ports:
  - port: 80
    targetPort: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: processing-orders-api-stable
  namespace: default
spec:
  selector:
    app: processing-orders-api
  ports:
  - port: 80
    targetPort: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: processing-orders-api-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: orders.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: processing-orders-api
            port:
              number: 80
